customhost = "employee.chenmz33ifdv.us-east-1.rds.amazonaws.com"
# customhost = "employee.cphh6ktzyzdt.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "sohzushen-employee"
# custombucket = "thampinnjie-employee"
customregion = "us-east-1"
